---
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

name: Release Management

jobs:
  ReleaseAutomation:
    
    runs-on: ubuntu-22.04

    steps:

      - uses: google-github-actions/release-please-action@v3
        id: release-please
        # skip during local actions testing
        if: ${{ !env.ACT }}
        with:
          release-type: simple
          extra-files: |
            VERSION
            Lampray/Filesystem/lampFS.h
      #
      # This step serves as an interop layer between the online and offline
      # when online, we use release-please and further execution is gated by the releases_created output
      # when offline, we skip release-please and set releases_created to true to test creating a release build
      - name: Declare Release Created
        id: release
        env:
            RELEASE_PLEASE_TAGNAME: ${{ steps.release-please.outputs.tag_name }}
            RELEASE_PLEASE_RELEASES_CREATED: ${{ steps.release-please.outputs.releases_created }}
        run: |
          if [ "${{ env.ACT }}" = "true" ]; then
            echo "OFFLINE: release created"
            echo "releases_created=true" >> $GITHUB_OUTPUT
            echo "release_tag=$(git describe --tags --abbrev=1)" >> $GITHUB_OUTPUT

          elif [ "${RELEASE_PLEASE_RELEASES_CREATED}" = "true" ]; then
            echo "ONLINE: release created"
            echo "releases_created=true" >> $GITHUB_OUTPUT
            echo "release_tag=${RELEASE_PLEASE_TAGNAME}" >> $GITHUB_OUTPUT

          else 
            echo "ONLINE: release not created"

          fi

      - name: Checkout
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: actions/checkout@v3

      - name: OS Deps
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: ./.github/actions/setup-os
      
      # Just let ASDF do its thing. It's far easier and more reliable than trying to do it ourselves.
      - name: Tooling
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        uses: ./.github/actions/setup-tooling
        with:
          SetupCommand: ./setup.sh
      
      - name: Build
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        run: |
          ./build.sh Debug

      # only upload the release artifact if we're online and not testing
      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ steps.release.outputs.release_tag }}
        run: |
          if [ "${{ env.ACT }}" = "true" ]; then
            echo "OFFLINE: skipping upload"
            cp -r ./build/Lamp ./build/Lampray-${RELEASE_TAG}
          else
            gh release upload ${RELEASE_TAG} ./build/Lampray#lamp-${RELEASE_TAG}
          fi

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: lampray-release-binary
          path: ./build/Lamp

  FlatPak:
    needs:
      - ReleaseAutomation
    runs-on: ubuntu-22.04

    container:
      # gnome-45
      # https://hub.docker.com/layers/bilelmoussaoui/flatpak-github-actions/gnome-45/images/sha256-16e884b42f6cfdbed3c2baaa3f2da621c7f4db25e53036b3b814ad0b67fcf5e2?context=explore
      image: bilelmoussaoui/flatpak-github-actions@sha256:16e884b42f6cfdbed3c2baaa3f2da621c7f4db25e53036b3b814ad0b67fcf5e2
      options: --privileged

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: lampray-release-binary

      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: lampray.flatpak
          manifest-path: org.github.chollingworth.Lampray.yml
          cache-key: flatpak-builder-${{ github.sha }}

      - uses: actions/upload-artifact@v4
        id: artifact-upload
        with:
          name: lampray-release-binary
          path: ./build/Lamp